### PR TITLE
Configure application with environment variables

### PR DESCRIPTION
**Pull request by rothgar**
I'm trying to make the docker container run with configuration from environment variables but running into a problem.

You can see the startup.sh script I added from this PR but after adding the configuration to application.properties the application still fails when I try to sign in.

Here is output from the application logs with this modified container.

```
twitter4j.TwitterException: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/sec
ret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

        at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:164) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at twitter4j.HttpClientBase.request(HttpClientBase.java:57) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at twitter4j.HttpClientBase.post(HttpClientBase.java:86) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:115) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:92) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at twitter4j.TwitterBaseImpl.getOAuthRequestToken(TwitterBaseImpl.java:292) ~[twitter4j-core-4.0.4.jar!/:4.0.4]
        at com.jeanchampemont.wtfdyum.service.impl.TwitterServiceImpl.signin(TwitterServiceImpl.java:164) ~[wtfdyum.jar!/:1.1.0-SNAPSHOT]
        at com.jeanchampemont.wtfdyum.web.MainController.signin(MainController.java:79) [wtfdyum.jar!/:1.1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72-internal]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72-internal]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72-internal]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.
4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) [spring-webmvc-4.
2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) [spring-webmvc-4.2.4.R
ELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.R
ELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72-internal]
```

I thought maybe you could help me figure out why I'm getting the errors.

I verified the application id and secret are correct and timezone is set (from my `docker run` example). Let me know if there's something else I can try help make the container easier for people to use in the future.

### CODE REVIEW

**Comment by jchampemont** [comment]
Thanks for your PR. I just tried to run the app with code from your PR, and it's working.

I first built your version of the container using `docker build -t rothgar-wtfdyum .` and then ran it with `docker run -it --rm -p 8080:8080 -e APPID=<MYAPPID> -e APPSECRET=<MYAPPSECRET> -v /etc/localtime:/etc/localtime:ro rothgar-wtfdyum`.

Are you sure you are using the correct values for `APPID` and `APPSECRET`?

For APPID, I'm using the "Consumer Key (API Key)" on "Keys and Access Tokens" tab of my twitter application.

For APPSECRET, I'm using the "Consumer Secret (API Secret)", on the same tab.

Also, as WTFDYUM is using Spring Boot, you don't need to write properties to `application.properties`. You can just override properties with environment variables. For example, this is how I am running WTFDYUM and Redis with docker-compose:

`docker-compose.yml`

```
version: '2'
services:
  redis:
    image: redis:3.0.7
  wtfdyum:
    image: jchampemont/wtfdyum:latest
    ports:
      - "8080:8080"
    links:
      - "redis:redis"
    env_file:
      - ./twitter.env
```

`twitter.env`

```
WTFDYUM_TWITTER_APPID=<APPID>
WTFDYUM_TWITTER_APPSECRET=<APPSECRET>
WTFDYUM_SERVER-BASE-URL=<http://app.url>
```

As you can see, any property like `my.property-value` can be overriden with an environment variable `MY_PROPERTY-VALUE`.

Hope this helps !

**Comment by rothgar** [comment]
Thanks that does help. I wasn't aware spring would automatically read from environment variables.
I also realized I was using the wrong APPID and secret. :confused: 
However, after fixing what I was doing wrong I tried setting the variables using your examples above and am still getting an error. (using your image and the one I was building)
selection_024
I think the problem may be with the callback URL. Inside the twitter configuration I don't have a value set. (I didn't know if it was necessary). I tried setting it to a machine on my lan but keep getting "The client application failed validation: Not a valid URL format." from twitter.
Does the server need a registered domain?

Once I get this figured out I'll probably close this PR and open a new one with better examples in the README. Hopefully you won't get people (like me) confused in the future.

**Comment by jchampemont** [comment]
Sorry about all this, I added the Dockerfile recently and did not had time to document it properly...

In case you did not read the install doc for non-docker environment, here it is: [INSTALL.md](https://github.com/jchampemont/WTFDYUM/blob/master/INSTALL.md)

About the callback URL, if I remember well, the value configured on apps.twitter.com is not relevant. The property `wtfdyum.server-base-url` is used to build the URL Twitter will redirect users to after signing in.

When developing on my machine, the value is `http://127.0.0.1:8080/`. When signing-in, Twitter will send a redirect to my browser to this URL. Twitter does NOT need to be able to contact this URL, but all clients should.

Typically, on live-internet environment, the value should be a registered domain.

**Comment by rothgar** [comment]
Thanks for the info. I haven't had a chance to verify your steps but they seem like they'd work. I'll go ahead and close this and just look into the default environment variables that spring boot provides.

**Pull request closed without merging**
